camera:
  sensor_id: 0
  width: 1640
  height: 1232
  framerate: 30
mavlink:
  connection: udpin:0.0.0.0:14551
  baud: 921600
  ground_station_ip: 100.112.124.116
  source_system: 1
  source_component: 191
  attitude_stream_rate_hz: 10
  sitl: true
video_link:
  host: 100.112.124.116
  port: 5005
mjpeg_server:
  enabled: true
  port: 8080
model:
  path: yolo26n.engine
  task: detect
detection:
  classes:
  - 62
  confidence: 0.65
tracker:
  backend: bytetrack
  config_file: bytetrack.yaml
  max_timeout_frames: 50
  deepsort:
    max_age: 50
    embedder: mobilenet
    half: false
    max_cosine_distance: 0.8
    n_init: 1
    max_iou_distance: 0.8
control:
  k_p_yaw: 0.84
  k_d_yaw: 0.0
  k_p_vz: 2.6
  k_d_vz: 0.0
  k_p_vx: 0.65
  k_d_vx: 0.0
  r_stop: 0.8
  yaw_deadzone: 0.06
  vz_deadzone: 0.02
  dist_deadzone: 0.1
  max_derivative_dt: 0.5
  hover_timeout: 10.0
  max_vx: 1.5
  max_vz: 1.0
  max_yaw_rate: 1.0
calibration:
  file: calibration.json
  desired_stopping_distance_m: 0.5
  optical_constant: 297608.78206863324
mission_behavior:
  min_takeoff_alt_m: 5.0
  hover_stability_time_s: 3.0
  hover_stability_threshold_m: 0.5
display:
  stream_width: 820
  stream_height: 616
  jpeg_quality: 60
  ground_station_window_width: 820
  ground_station_window_height: 616
target_selection:
  mode: auto
command_link:
  jetson_host: 100.109.108.81
  port: 5006
pitch_compensation:
  mode: gimbal_auto
