camera:
  sensor_id: 0
  width: 1280
  height: 960
  framerate: 30
mavlink:
  # connection: /dev/ttyACM0       # Physical Pixhawk via USB serial
  connection: udpin:0.0.0.0:14551  # MAVProxy UDP stream
  telemetry_output: udpout:172.29.249.199:14560
  source_system: 2
  source_component: 191
  attitude_stream_rate_hz: 10
video_link:
  host: 172.29.249.199
  port: 5005
model:
  path: yolo26n.engine
  task: detect
detection:
  classes:
  - 62
  confidence: 0.65
tracker:
  backend: bytetrack
  config_file: bytetrack.yaml
  max_timeout_frames: 50
  deepsort:
    max_age: 50
    embedder: mobilenet
    half: false
    max_cosine_distance: 0.8
    n_init: 1
    max_iou_distance: 0.8
control:
  k_p_yaw: 4.231974921630094
  k_d_yaw: 0.3887147335423197
  k_p_vz: 3.714733542319749
  k_d_vz: 0.5266457680250783
  k_p_vx: 1.5517241379310347
  r_stop: 0.8
  yaw_deadzone: 0.03
  vz_deadzone: 0.03
  area_deadzone: 0.05
  max_derivative_dt: 0.5
  k_d_vx: 0.9529780564263323
calibration:
  file: calibration.json
  desired_stopping_distance_m: 0.6
  optical_constant: 7192.943181818182
  frames_per_sample: 30
display:
  stream_width: 640
  stream_height: 480
  jpeg_quality: 60
  ground_station_window_width: 1280
  ground_station_window_height: 720
target_selection:
  mode: manual
command_link:
  jetson_host: 172.29.249.164
  port: 5006
pitch_compensation:
  mode: software  # 'software', 'gimbal_auto', 'gimbal_manual', or 'none'
